<?php
$typeArr[1] = '电视剧剧情';
$typeArr[2] = '分集剧情';
$typeArr[3] = '内地剧情介绍';
$typeArr[4] = '港台剧情介绍';
$typeArr[5] = '日韩剧情介绍';
$typeArr[6] = '泰剧剧情介绍';
$typeArr[7] = '欧美剧情介绍';
$typeArr[8] = '电影剧情';
$typeArr[9] = '演员表';
$typeArr[10] = '影视动态';
$typeArr[11] = '春暖花又开';
$typeArr[12] = '都挺好';
$typeArr[13] = '只为遇见你';
$typeArr[14] = '冷案';
$typeArr[15] = '黄金瞳';
$typeArr[16] = '泰剧天使之恋';
$typeArr[17] = '泰剧心之影';
$typeArr[18] = '剧情介绍';
$typeArr[19] = '分集剧情';
$typeArr[20] = '演员表';
?>