<li class="silder_panel clearfix">
                <a href="[field:arcurl/]" class="FL">
                    <img alt="都挺好" src="[field:picname/]">
                </a>
                <div class="silder_intro FR">
                    <h3><strong><a href="http://www.juqingba.cn/zjuqing/68163.html">都挺好</a></strong> <span>集数：46集</span></h3>
                    <ul>
                        <li><label>类型：</label><span>都市 情感</span></li>
                        <li><label>导演：</label><span>简川訸</span></li>
                        <li><label>主演：</label><span>姚晨 倪大红 郭京飞 杨祐宁</span></li>
                    </ul>
                    <p>[<strong>剧情介绍</strong>]讲述了职场金领苏明玉从小不受家人待见，生长在家庭的边缘，在孤独扭曲的环境中长...</p>
                    <a class="silder_play" target="_blank" href="http://www.juqingba.cn/zjuqing/68163.html">详细介绍</a>
                </div>
            </li>