<li class="silder_panel clearfix">
                <a href="[field:arcurl/]" class="FL">
                    <img alt="[field:title/]" src="[field:picname/]">
                </a>
                <!--<div class="silder_intro FR">-->
                    <!--<h3><strong><a href="[field:arcurl/]">[field:title/]</a></strong> <span>集数：46集</span></h3>-->
                    <!--<ul>-->
                        <!--<li><label>类型：</label><span>都市 情感</span></li>-->
                        <!--<li><label>导演：</label><span>简川訸</span></li>-->
                        <!--<li><label>主演：</label><span>姚晨 倪大红 郭京飞 杨祐宁</span></li>-->
                    <!--</ul>-->
                    <!--<p>[<strong>剧情介绍</strong>][field:info/]...</p>-->
                    <!--<a class="silder_play" target="_blank" href="[field:arcurl/]">详细介绍</a>-->
                <!--</div>-->
            </li>