<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",170,187);
$z[1][4]=array();
$z[2]=Array("arcurl","",202,217);
$z[2][4]=array();
$z[3]=Array("title","",233,247);
$z[3][4]=array();
$z[4]=Array("pubdate","",293,339);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",361,375);
$z[5][4]=array();
$z[6]=Array("scores","",397,412);
$z[6][4]=array();
$z[7]=Array("description","",445,465);
$z[7][4]=array();

?>