<?php
$z[0]=Array("global","(@me % 5 == 0)?@me=\"<li class=\\\"hr\\\">\":@me=\"<li>\";",4,111);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",135,182);
$z[1][4]=array();
$z[1][4]['function']="MyDate('y-m-d',@me)";
$z[2]=Array("typelink","",221,238);
$z[2][4]=array();
$z[3]=Array("arcurl","",289,304);
$z[3][4]=array();
$z[4]=Array("typename","",306,323);
$z[4][4]=array();

?>