-->
            <!--<li class="silder_panel clearfix">-->
                <!--<a href="[field:arcurl/]" class="FL">-->
                    <!--[field:image/]</a>-->
                <!--<div class="silder_intro FR">-->
                    <!--<h3><strong><a href="[field:arcurl/]">[field:typename/]</a></strong>-->
                        <!--<span>集数：76集</span></h3>-->
                    <!--<ul>-->
                        <!--<li><label>类型：</label><span>言情 古装 励志</span></li>-->
                        <!--<li><label>导演：</label><span>张开宙</span></li>-->
                        <!--<li><label>主演：</label><span>赵丽颖 冯绍峰 朱一龙 施诗</span></li>-->
                    <!--</ul>-->
                    <!--<p>[<strong>剧情介绍</strong>][field:info/]...</p>-->
                    <!--<a class="silder_play" target="_blank" href="[field:arcurl/]">详细介绍</a>-->
                <!--</div>-->
            <!--</li>-->
            <!--