<?php
$z[0]=Array("global","",118,145);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",178,210);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",354,379);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("hotwords","",1489,1541);
$z[3][4]=array();
$z[3][4]['num']="7";
$z[3][4]['maxlength']="12";
$z[3][4]['subday']="365";
$z[4]=Array("tag","\n                <a href='[field:link/]'>[field:tag /]</a>\n                ",1561,1690);
$z[4][4]=array();
$z[4][4]['row']="10";
$z[4][4]['getall']="1";
$z[4][4]['sort']="month";
$z[5]=Array("global","",1848,1875);
$z[5][4]=array();
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",1971,1998);
$z[6][4]=array();
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",2141,2168);
$z[7][4]=array();
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("channel","\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\n        ",2192,2324);
$z[8][4]=array();
$z[8][4]['row']="10";
$z[8][4]['type']="top";

?>